# Fly.io deployment configuration
app = "slackcrm-backend"
primary_region = "iad" # US East

[build]
  dockerfile = "backend/Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false # Keep running (don't sleep)
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "10s"
    method = "GET"
    path = "/health/readiness"

# Resource allocation (free tier)
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256

# Auto-scaling (free tier allows up to 3 VMs)
[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.http_checks]]
    interval = 30000
    timeout = 5000
    grace_period = 10000
    method = "GET"
    path = "/health/readiness"
