services:
  # Backend API (Free Tier - 750 hours/month)
  - type: web
    name: slackcrm-backend
    env: node
    region: oregon
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /health/readiness
    envVars:
      # Application
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

      # Database (Use Neon - add your DATABASE_URL in Render dashboard)
      - key: DATABASE_URL
        sync: false  # Set this in Render dashboard with your Neon URL
      - key: DB_SSL
        value: true
      - key: DB_SYNC
        value: false
      - key: DB_LOGGING
        value: false

      # Stack Auth (Set these in Render dashboard)
      - key: NEXT_PUBLIC_STACK_PROJECT_ID
        value: c0256b4b-12d4-44ad-9eea-126af89d909c
      - key: NEXT_PUBLIC_STACK_PUBLISHABLE_CLIENT_KEY
        value: pck_1h7wrs1bjk6g7pw2n8gmhvz62mv6tbp9p6cwzshde3h6g
      - key: STACK_SECRET_SERVER_KEY
        sync: false  # Set this in Render dashboard

      # JWT Secrets (will be auto-generated by Render)
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 24h
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d

      # URLs (update after deployment)
      - key: APP_URL
        sync: false  # Set to your Render backend URL
      - key: FRONTEND_URL
        sync: false  # Set to your Vercel frontend URL

      # Email (Optional - set if you have SendGrid)
      - key: SENDGRID_API_KEY
        sync: false
      - key: FROM_EMAIL
        value: noreply@slackcrm.app

      # Integrations (Optional)
      - key: SLACK_CLIENT_ID
        sync: false
      - key: SLACK_CLIENT_SECRET
        sync: false
      - key: TYPEFORM_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false

      # Redis (Optional - for queues, can skip for now)
      # - key: REDIS_HOST
      #   sync: false
      # - key: REDIS_PORT
      #   value: 6379
